version: '3'

services:
  website:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" --reload "ensimpl_snps.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/app/ensimpl_snps'
      - ${ENSIMPL_SNPS_DATA}:/app/ensimpl_snps/data
    ports:
      - '${EXTERNAL_PORT}:8000'
